# Generated by Django 4.0.3 on 2022-04-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favoritedRecipe', models.CharField(max_length=255)),
                ('costOfIngredients', models.DecimalField(decimal_places=2, max_digits=6)),
                ('bestByDate', models.DateField()),
                ('expiredIngredients', models.IntegerField()),
            ],
        ),
    ]
